<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4018.5">
  <POU Name="MAIN" Id="{b35740f0-740b-4f7e-bcd7-59db9c475d00}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[PG_Time();
PG_Alarm();
PG_Calculate_Sun();
PG_Rain();
PG_Heizung();
Visu();
PG_Besucher();
IF TRUE THEN
	PG_SimulationsHaus();
END_IF
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>